### ISSUE TITLE
请教大佬，请问如何指定相应的输入法，比如搜狗等，谢谢

### ISSUE THREAD

**Issue by caesarljs** [Yufeikang/autoSwitchIputMethod#1]
最近正在被这个输入法困扰，在github刚好看到您的方法，想请问一下，如何指定特定的输入法呢，比如我想让搜狗输入法的中文输入作为我的默认输入法，这个不知道怎么解决
恳请大佬赐教，谢谢
祝好

**Comment by yufeikang** [comment]
抱歉，貌似没办法实现，如你有方案，欢迎交流，谢谢

**Comment by caidaoli** [comment]
可以参考一下我的配置，我默认是英文，微信使用搜狗
{
    "default": "com.apple.keylayout.US",
    "appConfig": {
      "com.sogou.inputmethod.sogou": [
        "Telegram",
        "微信"
      ],
      "com.apple.keylayout.US": [
        "Code"
      ]
    }
  }

**Comment by caidaoli** [comment]
在终端中直接运行 .quiet_input_method/quiet会输出日志，能看到安装的输入法。
Listening for app switch events...
com.apple.CharacterPaletteIM
com.apple.keylayout.US
com.apple.PressAndHold
com.sogou.inputmethod.sogou.pinyin
com.sogou.inputmethod.sogou
Current app: Firefox to com.apple.keylayout.US
Switching to com.apple.keylayout.US
Current app: iTerm2 to com.apple.keylayout.US
Switching to com.apple.keylayout.US
Current app: Firefox to com.apple.keylayout.US
Switching to com.apple.keylayout.US
Current app: iTerm2 to com.apple.keylayout.US
Switching to com.apple.keylayout.US
Current app: Firefox to com.apple.keylayout.US
Switching to com.apple.keylayout.US
Current app: iTerm2 to com.apple.keylayout.US
Switching to com.apple.keylayout.US
Current app: 微信 to com.sogou.inputmethod.sogou
Switching to com.sogou.inputmethod.sogou.pinyin
Current app: iTerm2 to com.apple.keylayout.US
Switching to com.apple.keylayout.US
