### ISSUE TITLE
sonoma 桌面panic

### ISSUE THREAD

**Issue by vincentchyu** [Yufeikang/autoSwitchIputMethod#2]
机器:Mac 2021 M1max 64g
version:14.2.1
出现场景:开启台前调度和自动切换输入法
出现问题:会出现桌面进入崩溃,转风车,所有操作失灵,智能强制重启电脑,

附言:其他的自动切换输入法和台前调动共同使用都会有当前问题,以前用input-source-pro,今天尝试用开源的,也就是这个,也有一样的问题

**Comment by yufeikang** [comment]
sorry. 我并不是一个macOS开发者，纯粹是为了这个小功能不想额外装个app而写的这个脚本，大部分逻辑也是Google到的。所以这个问题可能无法帮到你。你可以尝试把panic日志发给chatGPT问问。
